[package]
name = "remud"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
tokio-util = { version = "0.6", features = ["codec"] }
futures = "0.3"
lazy_static = "1.4.0"
bitflags = "1.3.2"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
