{
 "title": "Remud",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Dashboard - Live", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Players",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-players",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Web Sockets",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "ws",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_ws_num_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Telnet",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "telnet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_telnet_num_clients",
     "query": "SELECT last(\"value\") FROM \"remud_telnet_num_clients\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tick Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "alias": "ms per iteration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-run-loop",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Input Latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-input",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Containers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "objects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-objects",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Prototypes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "objects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-prototypes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Rooms",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "objects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-rooms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "# Scripts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "objects",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-scripts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Details Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "# connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "telnet",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_telnet_num_clients",
     "query": "SELECT last(\"value\") FROM \"remud_telnet_num_clients\" WHERE $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "ws",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_ws_num_clients",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "total players",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "remud_num-players",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "run-loop",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-run-loop",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "reload-prototypes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-reload-prototypes",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "process-input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-input",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "process-connect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-connect",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "process-ready",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-ready",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "process-password-verify",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-password-verification",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "tick-metrics",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-tick-metrics",
     "query": "SELECT last(\"mean\") FROM \"remud_run-loop\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "telnet connect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_telnet_client_connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "telnet disconnect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_telnet_client_disconnected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "ws connect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_ws_client_connected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "ws disconnect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_ws_client_disconnected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Scripts API Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "create",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-web-create-script",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "read all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-web-read-all-scripts",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-web-read-script",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "update",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-web-update-script",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "delete",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_engine-process-web-delete-script",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Script Executions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "init",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-init",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "pre-event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-pre-event\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "post-event",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-post-event",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-post-event\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "timed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-init",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-timed\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "pre-event errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-timed\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "post-event errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-post-event_error\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Script Execution Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "pre-event errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-timed\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "post-event errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-post-event_error\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "timed errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-timed_error\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "init errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "remud_scripts_run-pre-event_error",
     "query": "SELECT mean(\"value\") FROM \"remud_scripts_run-init_error\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docker CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Docker Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_mem\" WHERE $timeFilter GROUP BY time($__interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "System CPU utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "usage_system",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "usage_user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "System utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "memory",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "disk space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}